# Generated by Django 5.0.6 on 2024-06-18 07:04

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disaster', '0001_initial'),
        ('response', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('ASSESSMENT', 'Assessment'), ('ATTACHED_FILE', 'Attached File')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MediaRoomConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('ASSESSMENT', 'Assessment'), ('ATTACHED_FILE', 'Attached File')], max_length=50)),
                ('aftermath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='response.aftermath')),
                ('disaster_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disaster.disasterevent')),
                ('media_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaroom.mediaroom')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='response.response')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
