# Generated by Django 5.0.6 on 2024-06-18 07:04

import dirtyfields.dirtyfields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_id', models.CharField(blank=True, editable=False, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('severity_level', models.FloatField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default='not yet provided')),
                ('status', models.CharField(choices=[('reported', 'REPORTED'), ('in_progress', 'IN_PROGRESS'), ('confirmed', 'CONFIRMED'), ('resolved', 'RESOLVED')], default='reported', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('affected_population', models.IntegerField(blank=True, null=True)),
                ('damage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('emergency_response_units', models.TextField(blank=True, null=True)),
                ('additional_resources_needed', models.TextField(blank=True, null=True)),
                ('relief_centers', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('unknown', 'UNKNOWN'), ('low', 'LOW'), ('moderate', 'MODERATE'), ('high', 'HIGH'), ('utmost', 'UTMOST')], default='unknown', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DisasterEventConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
