# Generated by Django 5.0.6 on 2024-06-16 16:25

import dirtyfields.dirtyfields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('severity', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
