# Generated by Django 5.0.6 on 2024-06-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disaster', '0001_initial'),
        ('mediaroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterevent',
            name='media_files',
            field=models.ManyToManyField(blank=True, through='mediaroom.MediaRoomConnector', to='mediaroom.mediaroom'),
        ),
        migrations.AddField(
            model_name='disastereventconnector',
            name='disaster_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.disasterevent'),
        ),
        migrations.AddField(
            model_name='disastereventconnector',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disasterevent',
            name='reporters',
            field=models.ManyToManyField(blank=True, through='disaster.DisasterEventConnector', to=settings.AUTH_USER_MODEL),
        ),
    ]
